#Intendencia
Charge.create(name: 'Intendente Regional')

#Administrador Regional
Charge.create(name: 'Administrador Regional')

#Consejo Regional
Charge.create(name: 'Asesor Consejo Regional')
Charge.create(name: 'Asesor Jurídico Consejo Regional')
Charge.create(name: 'Secretario Ejecutivo Consejo Regional')
Charge.create(name: 'Profesional Consejo Regional')
Charge.create(name: 'Administrativo Consejo Regional')
Charge.create(name: 'Administrativa Consejo Regional')
Charge.create(name: 'Periodista Consejo Regional')
Charge.create(name: 'Recepcionista Consejo Regional')

#Resto del GORE
Charge.create(name: 'Encargado Comunicaciones')
Charge.create(name: 'Reportero Gráfico')
Charge.create(name: 'Asesor Intendente')
Charge.create(name: 'Coordinador')
Charge.create(name: 'Coordinador Programa')
Charge.create(name: 'Coordinadora')
Charge.create(name: 'Coordinadora Programa')
Charge.create(name: 'Jefe')
Charge.create(name: 'Jefa')
Charge.create(name: 'Encargado')
Charge.create(name: 'Encargado Unidad de Gestión Información Territorial')
Charge.create(name: 'Profesional en Gestión y Manejo de Recursos Naturales en Ecosistemas Marinos y Lacustres')
Charge.create(name: 'Analista de Sistemas de Información Territorial Geografico')
Charge.create(name: 'Profesional de Apoyo a Municipios y Preinversión')
Charge.create(name: 'Profesional del Programa de Infraestructura Rural para el Desarrollo Territorial')
Charge.create(name: 'Encargada')
Charge.create(name: 'Profesional')
Charge.create(name: 'Profesional Programa')
Charge.create(name: 'Técnico')
Charge.create(name: 'Técnico Programa')
Charge.create(name: 'Administrativo')
Charge.create(name: 'Administrativo Contable')
Charge.create(name: 'Administrativo Programa')
Charge.create(name: 'Administrativa')
Charge.create(name: 'Administrativa Contable')
Charge.create(name: 'Administrativa Programa')
Charge.create(name: 'Secretario')
Charge.create(name: 'Secretaria')
Charge.create(name: 'Abogada')
Charge.create(name: 'Abogado')
Charge.create(name: 'Asesor')
Charge.create(name: 'Asesora')
Charge.create(name: 'Asesora Jurídica')
Charge.create(name: 'Apoyo Administrativo')
Charge.create(name: 'Analista de Inversiones')
Charge.create(name: 'Profesional Porgrama Electrificación Rural')
Charge.create(name: 'Profesional del Programa de Residuos Sólidos')
Charge.create(name: 'Profesional del Programa de Saneamiento Sanitario')
Charge.create(name: 'Tecnico del Programa de Saneamiento Sanitario')
Charge.create(name: 'Programador FNDR')
Charge.create(name: 'Apoyo Programador FNDR')
Charge.create(name: 'Administrativo Of. Partes y SAIP')
Charge.create(name: 'Administrativo Of. Partes')
Charge.create(name: 'Profesional Encargada Prog. 01')
Charge.create(name: 'Tesorero Prog. 01')
Charge.create(name: 'Tesorero Prog. 02')
Charge.create(name: 'Apoyo Contable')
Charge.create(name: 'Asesor Informático')
Charge.create(name: 'Diseño y Producción Gráfica')
Charge.create(name: 'Apoyo Unidad')
Charge.create(name: 'Amplificación y equipos audiovisuales')
Charge.create(name: 'Recepcionista')
Charge.create(name: 'Conductor')
