Charge.create(name: 'Intendente Regional')
Charge.create(name: 'Administrador Regional')
Charge.create(name: 'Asesor Consejo Regional')
Charge.create(name: 'Asesor Jurídico Consejo Regional')
Charge.create(name: 'Secretario Ejecutivo Consejo Regional')
Charge.create(name: 'Profesional Consejo Regional')
Charge.create(name: 'Administrativo Consejo Regional')
Charge.create(name: 'Administrativa Consejo Regional')
Charge.create(name: 'Periodista Consejo Regional')
Charge.create(name: 'Recepcionista Consejo Regional')
Charge.create(name: 'Encargado Comunicaciones')
Charge.create(name: 'Reportero Gráfico')
Charge.create(name: 'Asesor Intendente')
Charge.create(name: 'Coordinador')
Charge.create(name: 'Coordinador Programa')
Charge.create(name: 'Coordinadora')
Charge.create(name: 'Coordinadora Programa')
Charge.create(name: 'Jefe')
Charge.create(name: 'Jefa')
Charge.create(name: 'Encargado')
Charge.create(name: 'Encargado Unidad de Gestión Información Territorial')
Charge.create(name: 'Profesional en Gestión y Manejo de Recursos Naturales en Ecosistemas Marinos y Lacustres')
Charge.create(name: 'Analista de Sistemas de Información Territorial Geografico')
Charge.create(name: 'Profesional de Apoyo a Municipios y Preinversión')
Charge.create(name: 'Profesional del Programa de Infraestructura Rural para el Desarrollo Territorial')
Charge.create(name: 'Encargada')
Charge.create(name: 'Profesional')
Charge.create(name: 'Profesional Programa')
Charge.create(name: 'Técnico')
Charge.create(name: 'Técnico Programa')
Charge.create(name: 'Administrativo')
Charge.create(name: 'Administrativo Contable')
Charge.create(name: 'Administrativo Programa')
Charge.create(name: 'Administrativa')
Charge.create(name: 'Administrativa Contable')
Charge.create(name: 'Administrativa Programa')
Charge.create(name: 'Secretario')
Charge.create(name: 'Secretaria')
Charge.create(name: 'Abogada')
Charge.create(name: 'Abogado')
Charge.create(name: 'Asesor')
Charge.create(name: 'Asesora')
Charge.create(name: 'Asesora Jurídica')
Charge.create(name: 'Apoyo Administrativo')
Charge.create(name: 'Analista de Inversiones')
Charge.create(name: 'Profesional Porgrama Electrificación Rural')
Charge.create(name: 'Profesional del Programa de Residuos Sólidos')
Charge.create(name: 'Profesional del Programa de Saneamiento Sanitario')
Charge.create(name: 'Tecnico del Programa de Saneamiento Sanitario')
Charge.create(name: 'Programador FNDR')
Charge.create(name: 'Apoyo Programador FNDR')
Charge.create(name: 'Administrativo Of. Partes y SAIP')
Charge.create(name: 'Administrativo Of. Partes')
Charge.create(name: 'Profesional Encargada Prog. 01')
Charge.create(name: 'Tesorero Prog. 01')
Charge.create(name: 'Tesorero Prog. 02')
Charge.create(name: 'Apoyo Contable')
Charge.create(name: 'Asesor Informático')
Charge.create(name: 'Diseño y Producción Gráfica')
Charge.create(name: 'Apoyo Unidad')
Charge.create(name: 'Amplificación y equipos audiovisuales')
Charge.create(name: 'Recepcionista')
Charge.create(name: 'Conductor')

Unit.create(name: 'Intendente')
Unit.create(name: 'Administración Regional')
Unit.create(name: 'Gabinete')
Unit.create(name: 'División de Fomento Productivo e Industrias')
Unit.create(name: 'Programa Fondo Innovación para la Competitividad')
Unit.create(name: 'Programa de Gestión Territorial para Zonas Rezagadas')
Unit.create(name: 'Consejo Regional de Los Ríos')
Unit.create(name: 'Departamento Jurídico')
Unit.create(name: 'Unidad de Auditoría Interna')
Unit.create(name: 'Unidad de Gestión Estratégica Institucional')
Unit.create(name: 'Organizaciones Sociales')
Unit.create(name: 'División de Presupuesto e Inversión Regional')
Unit.create(name: 'Unidad de Subvenciones')
Unit.create(name: 'Departamento de Gestión e Inversiones')
Unit.create(name: 'Unidad de Programación')
Unit.create(name: 'Unidad FRIL')
Unit.create(name: 'Departamento de Presupuesto')
Unit.create(name: 'División de Administración y Finanzas')
Unit.create(name: 'Departamento de Gestión y Desarrollo de Personas')
Unit.create(name: 'Oficina de Partes')
Unit.create(name: 'Departamento de Finanzas')
Unit.create(name: 'Unidad de Adquisiciones')
Unit.create(name: 'Unidad de Informática')
Unit.create(name: 'Unidad de Servicios Generales')
Unit.create(name: 'División de Planificación y Desarrollo Regional')
Unit.create(name: 'Departamento de Planificación Estratégica')
Unit.create(name: 'Unidad Regional de Asuntos Internacionales (URAI)')
Unit.create(name: 'Departamento de Ordenamiento Territorial')
Unit.create(name: 'Unidad de Coordinación de la Inversión')
Unit.create(name: 'Programa de Infraestructura Rural')
Unit.create(name: 'Participación Ciudadana')

Division.create(name: 'Intendente')
Division.create(name: 'Administración Regional')
Division.create(name: 'Gabinete')
Division.create(name: 'División de Fomento Productivo e Industrias')
Division.create(name: 'Consejo Regional de Los Ríos')
Division.create(name: 'Jurídica')
Division.create(name: 'Auditoría Interna')
Division.create(name: 'Gestión Estratégica Institucional')
Division.create(name: 'Organizaciones Sociales')
Division.create(name: 'División de Presupuesto e Inversión Regional')
Division.create(name: 'División de Administración y Finanzas')
Division.create(name: 'División de Planificación y Desarrollo Regional')
